name: Build iOS IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest # ¡Aquí está la magia! Usamos un Mac de GitHub
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar App (Sin firmar)
        # Esto crea el archivo Payload necesario para AltStore
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload
          zip -r TuneX.ipa Payload

      - name: Subir el archivo IPA para descargar
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/TuneX.ipa
